### ISSUE TITLE
Allow for includes/excludes and multiple file content in RequiresFileContent

### ISSUE THREAD

**Issue by qbaze** [ceilfors/enforcer-rules#5]
Hi,

I've been looking for something similar to your rule but with an extended functionality. I've modified your code a bit to allow for wildcard includes and excludes and multiple content and was wondering if you're interested in including it in your codebase. Let me know.

Cheers,
Piotr

**Comment by maddingo** [comment]
Of course, improvements are welcome. Just create a pull request.
Thanks.

**Comment by ceilfors** [comment]
@qbaze That sounds great. Please submit your change of code via pull request.
